### ISSUE TITLE
FEAT: hover,docs,etc for keycodes etc

### ISSUE THREAD

**Issue by IndianBoy42** [codethread/qmk.nvim#12]
I wonder if this plugin could help with setting up the clangd lsp for working in qmk. that and/or it could provide commands/highlights for some useful things like what certain KC_CODE mean in a floating hover window kj

**Comment by codethread** [comment]
Hey thanks for the suggestion 😄 

I'm afraid I'll be keeping this package closely scoped to just handling keycode manipulation and will leave more complex matters like lsp integration to users. This will stop the package from growing beyond my means to maintain 😅 . 

It will also get more difficult as the number of hardware targets increases; right now it's QMK and ZMK, one is `c` using clang, but the other is a custom `devicetree` filetype, and there is also one (which I can't remember) written in `python`
