### ISSUE TITLE
[E06] Not enough keys in the keymap for your configured layout (ZMK)

### ISSUE THREAD

**Issue by benfrain** [codethread/qmk.nvim#22]
Sorry, another beginner question but further to #21 I now keep getting this error.

I have written my config a couple of ways, but to no avail. This is what I have currently in Lua to represent the keymap:

```lua
      local conf = {
        name = "LAYOUT_pretty",
        variant = "zmk",
        layout = {
          "x x x x x x x _ _ _ _ _ _ _ _ _ _ x x x x x x x",
          "x x x x x x x _ _ _ _ _ _ _ _ _ _ x x x x x x x",
          "x x x x x x x _ x x x _ _ x x x _ x x x x x x x",
          "x x x x x x _ x x x x _ _ x x x x _ x x x x x x",
          "x x x x x _ _ _ x x x _ _ x x x _ _ _ x x x x x",
        },
      }
```

And here is the keymap I am trying to use it on: https://github.com/benfrain/Adv360-Pro-ZMK/blob/V2.0/config/adv360.keymap

Realise there is likely something obvious I am missing!

**Comment by codethread** [comment]
I'm pretty baffled 😅 your config looks correct. Though it does contain 84 keys, but when I look at your keymap, I can only count 82 in the first keymap. I think 84 is correct though, as when I use your config with the [Kinesis corp config](https://github.com/KinesisCorporation/Adv360-Pro-ZMK/blob/V2.0/config/adv360.keymap), that works and does indeed contain 84 keys.

Could you maybe have dropped a key in your config somewhere? Is there some macro, or ZMK magic that fills in the missing keys?

I've pasted below what the plugin sees (and it looks correct to me, I can't see any obvious accidental joining of keys). 

I've also created a branch `tmp-debug-zmk` which will allow you to set `log = true`, and that will write to `~/qmk.log` what the plugin is seeing when you run `QMKFormat`, no pressure to use it 😅  just hope it might help, and I will look to find a better way for users to debug in future

example config for branch `tmp-debug-zmk` :

```lua
		require('qmk').setup {
			name = 'LAYOUT_preonic_grid',
			variant = 'zmk',
			log = true,
			layout = {
				'x x x x x x x _ _ _ _ _ _ _ _ _ _ x x x x x x x',
				'x x x x x x x _ _ _ _ _ _ _ _ _ _ x x x x x x x',
				'x x x x x x x _ x x x _ _ x x x _ x x x x x x x',
				'x x x x x x _ x x x x _ _ x x x x _ x x x x x x',
				'x x x x x _ _ _ x x x _ _ x x x _ _ _ x x x x x',
			},
		}
```

what the plugin currently sees:

```lua
local output = {
	{
		keys = {
			'&mt LC(LG(LS(LALT))) DELETE',
			'_AS(N1)',
			'_AS(N2)',
			'_AS(N3)',
			'_AS(N4)',
			'_AS(N5)',
			'_AS(F11)',
			'_AS(F12)',
			'_AS(N6)',
			'_AS(N7)',
			'_AS(N8)',
			'_AS(N9)',
			'_AS(N0)',
			'_AS(LBKT)',
			'_AS(TAB)',
			'_AS(Q)',
			'_AS(W)',
			'_AS(F)',
			'_AS(P)',
			'_AS(B)',
			'_AS(BSLH)',
			'&bl BL_TOG',
			'_AS(J)',
			'_AS(L)',
			'_AS(U)',
			'_AS(Y)',
			'_AS(SEMI)',
			'_AS(RBKT)',
			'&mt LCTRL ESC',
			'_AS(A)',
			'_AS(R)',
			'_AS(S)',
			'_AS(T)',
			'_AS(G)',
			'&mm',
			'&kp LCTRL',
			'&cpy',
			'&kp RCMD',
			'&kp RCTRL',
			'&me',
			'_AS(M)',
			'_AS(N)',
			'_AS(E)',
			'_AS(I)',
			'_AS(O)',
			'&kp BSPC',
			'&mt LSHFT PG_UP',
			'_AS(Z)',
			'_AS(X)',
			'_AS(C)',
			'_AS(D)',
			'_AS(V)',
			'&none',
			'&none',
			'&kp HOME',
			'&none',
			'&none',
			'&kp END',
			'&none',
			'&none',
			'_AS(K)',
			'_AS(H)',
			'_AS(COMMA)',
			'_AS(DOT)',
			'_AS(FSLH)',
			'&mt RSHFT PG_DN',
			'&mo 1',
			'&none',
			'&kp LCTRL',
			'&kp LALT',
			'&mt LCMD GRAVE',
			'&kp LA(BSPC)',
			'&kp SPACE',
			'&mt LC(LG(LS(LALT))) SQT',
			'&mt RALT DQT',
			'&kp RET',
			'&kp BSPC',
			'&kp LEFT',
			'&kp DOWN',
			'&kp UP',
			'&kp RIGHT',
			'&kp TILDE',
		},
		layer_name = 'default_layer',
		layout_name = 'ZMK',
		pos = {
			final = 80,
			start = 74,
		},
	},
	{
		keys = {
			'&none',
			'&kp F1',
			'&kp F2',
			'&kp F3',
			'&kp F4',
			'&kp F5',
			'&kp F11',
			'&kp F12',
			'&kp F6',
			'&kp F7',
			'&kp F8',
			'&kp F9',
			'&kp F10',
			'&none',
			'&bt BT_CLR',
			'&bt BT_SEL 0',
			'&bt BT_SEL 1',
			'&bt BT_SEL 2',
			'&bt BT_SEL 3',
			'&bt BT_SEL 4',
			'&bt BT_SEL 5',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&bootloader',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&bootloader',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'_AS(BSLH)',
			'&none',
			'&mo 0',
			'&none',
			'&none',
			'&none',
			'&none',
			'&kp C_PLAY_PAUSE',
			'&none',
			'&none',
			'&none',
			'&none',
			'&none',
			'&kp C_PREV',
			'&kp C_VOLUME_DOWN',
			'&kp C_VOLUME_UP',
			'&kp C_NEXT',
			'&none',
		},
		layer_name = 'layer_keypad',
		layout_name = 'ZMK',
		pos = {
			final = 90,
			start = 84,
		},
	},
}
```

**Comment by benfrain** [comment]
Thanks! I'll try and track down those missing 2 keys :D

Looks like plugin is correct and 'error between keyboard and chair` — what most of my 'issues' end up being ;)

**Comment by codethread** [comment]
Ended up discovering your review on YouTube when I was Googling for this keyboard layout 😅 great video! I didn't know it was the standard for the 360, I assumed ZMK was for more hardcore mech board users; knowing that people might be forced to use it has made me realise the error messages need to be a lot more helpful, as I can imagine a lot of non techies trying to just get their keyboard to work 🤔

**Comment by benfrain** [comment]
Thanks for looking at this, adding the extra keys and all good now, thanks!
