### ISSUE TITLE
Issue with Kinesis Advantage360 config

### ISSUE THREAD

**Issue by steinbrueckri** [codethread/qmk.nvim#25]
Hi, I have a problem when I call `:QMKFormat` the comment block is inserted without any error message, what is good I hoop 😅, but the keys in the comment block are a bit off. Im not sure if I use the plugin in the wrong way or if this is really a but. 

This is how my Layout looks within the Kinesis Keymap Editor
<img width="2221" alt="Bildschirmfoto 2023-07-06 um 11 03 17" src="https://github.com/codethread/qmk.nvim/assets/578303/d4467d82-ca14-4fc2-b15d-b04ea701f108">

This is how my config file looks **before** `:QMKFormat`
<img width="2560" alt="Bildschirmfoto 2023-07-06 um 11 03 47" src="https://github.com/codethread/qmk.nvim/assets/578303/015f9ac2-f93d-4885-ae02-9f3b74455d32">

This is how my config file looks **after** `:QMKFormat`
<img width="2560" alt="Bildschirmfoto 2023-07-06 um 11 04 11" src="https://github.com/codethread/qmk.nvim/assets/578303/9f542c6f-e4a0-4c22-8404-5637e4c87c8a">

My `adv360.keymap` config is this https://github.com/steinbrueckri/Adv360-Pro-ZMK/blob/29c0f147ff40fe57c12235571f45da74bab96d7b/config/adv360.keymap#L40

## [`qmk.nvim` Config]( https://github.com/steinbrueckri/dotfiles/blob/master/.config/nvim/lua/plugins/zmk.lua): 

I have stolen this configuration from #21 #22

```
local conf = {
  name = "LAYOUT_pretty",
  variant = 'zmk',
  layout = {
    "x x x x x x x _ _ _ _ _ _ x x x x x x x",
    "x x x x x x x _ _ _ _ _ _ x x x x x x x",
    "x x x x x x x _ _ _ _ _ _ x x x x x x x",
    "x x x x x x _ _ _ _ _ _ _ _ x x x x x x",
    "x x x x x _ _ _ _ _ _ _ _ _ _ x x x x x",
    "_ _ _ _ _ _ x x _ _ _ _ x x _ _ _ _ _ _",
    "_ _ _ _ _ _ _ x _ _ _ _ x _ _ _ _ _ _ _",
    "_ _ _ _ _ x x x _ _ _ _ x x x _ _ _ _ _",
  }
}

require("qmk").setup(conf)
```

**Comment by codethread** [comment]
Hey @steinbrueckri thanks for raising 😃 

The `conf.layout` needs to match the layout your keymap is typed in, so looking at your keymap you want:

```lua
local conf = {
			variant = 'zmk',
			layout = {
				'x x x x x x x _ _ _ _ _ _ x x x x x x x',
				'x x x x x x x _ _ _ _ _ _ x x x x x x x',
				'x x x x x x x x x _ _ x x x x x x x x x',
				'x x x x x x _ _ x _ _ x _ _ x x x x x x',
				'x x x x x _ x x x _ _ x x x _ x x x x x',
			},
		}
```

if you want the layout to look more like the example you copied, you'd need to move the keys down in your keymap
(for context this plugin has no idea what is and isn't a valid keymap configuration, it's just dividing the keys into rows and columns, so the `conf.layout` is just that grid written out as a string where `x` marks a key, and `_` marks a space)

hope that helps, if you need any further help, let me know, if this solves your issue, please kindly close, thanks 😇

**Comment by steinbrueckri** [comment]
@codethread works like a charm. 🙏 ❤️
