### ISSUE TITLE
LazyVim Question

### ISSUE THREAD

**Issue by dedguy21** [codethread/qmk.nvim#32]
Can't see documentation on how to import this plugin with LazyVim.

How does that work, I keep getting errors. 

Thank you.

**Comment by codethread** [comment]
something like
```lua
	{
		'codethread/qmk.nvim',
		ft = { 'c' },
		config = function()
			---@type qmk.UserConfig
			local conf = {
				name = 'LAYOUT_preonic_grid',
				layout = {
					'_ x x x x x x _ x x x x x x',
					'_ x x x x x x _ x x x x x x',
					'_ x x x x x x _ x x x x x x',
					'_ x x x x x x _ x x x x x x',
					'_ x x x x x x _ x x x x x x',
				},
			}
			require('qmk').setup(conf)
		end,
	},
```

should work - I don't use LazyVim, but this is my config for lazy.nvim, so I believe they are the same

**Comment by dedguy21** [comment]
Thanks. 

Have a dactyl . 

Haven't tried configuring it in Neovim. 

My layout looks like:

```
 # keyboard
    xxxxxx_xxxxxx
    xxxxxx_xxxxxx
    xxxxxx_xxxxxx
       xx     _  xx
# thumb cluster
   xxx      -      xxx

```

**Comment by codethread** [comment]
ah I'm guessing through ZMK? if so you'll also need `variant = zmk` like in this [test example](https://github.com/codethread/qmk.nvim/blob/main/lua/qmk_spec.lua#L124)

also ZMK is quite experimental at this point because I don't have a ZMK device 😅 so hard to be confident it works. Let me know if you have any further issues - just drop your exact config and I'll be able to debug 😇

**Comment by codethread** [comment]
going to close this for now 😄 but please feel free to reopen if you come back to this and are getting errors 

thanks for checking out the plugin!

**Comment by joebonneau** [comment]
Hi @codethread -

I'm attempting to use this plugin, also with lazy nvim. The error I'm getting is this: 

```
qmk.nvim: [E02] Found more than one keymap declaration  
```

Here's my config:

```lua
return {
  "codethread/qmk.nvim",
  ft = { "c" },
  config = function()
    ---@type qmk.UserConfig
    local conf = {
      name = "LAYOUT_split_3x5_2",
      layout = {
        "x x x x x _ _ _ _ x x x x x",
        "x x x x x _ _ _ _ x x x x x",
        "x x x x x _ _ _ _ x x x x x",
        "_ _ _ _ x x _ _ x x _ _ _ _",
      },
    }
    require("qmk").setup(conf)
  end,
}

```

Any thoughts? Thanks in advance!

**Comment by codethread** [comment]
Hey 😊 could you post your keymap file?

**Comment by dein0s** [comment]
@joebonneau try commenting out encoder section, i'm having the same issue and commenting out encoder mapping fixed the issue

**Comment by codethread** [comment]
@dein0s thanks for identifying a workaround 😄 
@joebonneau this is an issue my end and I'll try to fix it in the coming days (can't promise anything in the run-up to Christmas, but will try my best! 🎅 )

**Comment by joebonneau** [comment]
Yep, commenting out the encoder section did the trick! Thanks for the suggestion @dein0s.
