### ISSUE TITLE
Trailing Whitespace

### ISSUE THREAD

**Issue by dhoizner** [codethread/qmk.nvim#33]
Hiya!

Got this set up today and the generated keymap looks wonderful.

I'm curious if there's anything I can do to avoid the trailing whitespace that's being inserted on format?

![Screenshot 2023-11-04 at 6 45 48 PM](https://github.com/codethread/qmk.nvim/assets/419620/47d7caa7-14e1-424e-b5ca-2f5c88b48b6b)

My layout is:
```json
{
  "name": "LAYOUT_all",
  "layout": [
    "x x x x x _ _ _ x x x x x x",
    "x x x x x _ _ _ x x x x x^x",
    "x^x x x x x _ _ _ x x x x x",
    "_ _ x x x x^x x^x x x x _ _"
  ],
  "comment_preview": {
    "keymap_overrides": {
      "SFT_T%(KC_BSPC%)": "S|BSPC"
    }
  }
}
```

Thanks!

**Comment by codethread** [comment]
Hey 😄 glad you're enjoying the plugin

How upsetting is this for you, and what sort of solution might work?

It's kind of non-trivial to trim the whitespace and might take some time, but I could very easily put something in at the end of each row so nothing is trailing. Do you think that would suffice? 

Another option might be to have some linter-related tool in your config that just removes trailing whitespace on save in all cases, and not just from the generated part... though I wonder if that might need to know to run after the keymaps are generated 😅

**Comment by Diaoul** [comment]
Enjoying the plugin as well but have the same issue. I have to disable other formatters so they don't interfere with the formatting done by `qmk.nvim` so unfortunately this is not an option for me.

**Comment by codethread** [comment]
Thanks for raising both. I've added it to the roadmap and I will find a solution when I'm next working on the project 🙂

**Comment by codethread** [comment]
🤞 should be solved now @Diaoul @dhoizner , please reopen if the issue persists 😄
